### PR TITLE
mount OPFS for persistence in playground

### LINKED ISSUE #43: Playground data is not persisted
Reloading the extension, wipes all data.

How to reproduce:

1. Comment out [these lines](https://github.com/WordPress/try-wordpress/blob/trunk/src/ui/preview/Playground.tsx#L76-L78), so that we don't delete all posts. (This code will also need to be adapted because this currently deletes all posts, but this is not the cause of the issue).
2. `npm run start`
3. In the Admin tab, create a post
4. Navigate to the list of posts, in the Admin, and verify that the post is there
5. Reload the extension through the browser developer tools (Cmd+R when the developer tools window is in focus)
6. Navigate to the list of posts, in the Admin.
7. The post that was created in 3. is not listed in the list of posts

### PR DESCRIPTION
**Pull request by ashfame**
This PR indicates playground to use an OPFS mount for persistence. It currently relies on localStorage to indicate playground whether it needs WP installed or not. In a future version, playground would handle this for us, so we will remove the localstorage bits.

Previous related PRs: #44 and #62
Fixes #43 

Props @akirk for localstorage hint to not wait for required change in Playground's api to land.

### CODE REVIEW

File: src/ui/preview/Playground.tsx [hunk 1]
```diff
@@ -55,9 +56,26 @@ async function initPlayground(
 	slug: string,
 	blogName: string
 ): Promise< PlaygroundClient > {
+	const mountDescriptor: MountDescriptor = {
+		device: {
+			type: 'opfs',
+			path: '/try-wp-' + slug,
```
Comment (ashfame) [inline src/ui/preview/Playground.tsx]: @psrpinto Should we nest this one level? `/try-wp-sites/{slug}`

File: src/ui/preview/Playground.tsx [hunk 2]
```diff
@@ -55,9 +56,26 @@ async function initPlayground(
...
+		},
+		mountpoint: '/wordpress',
+	};
+
+	let isWordPressInstalled = false;
+	if ( localStorage.getItem( 'isWordPressInstalled' ) !== null ) {
+		isWordPressInstalled = true;
+	}
+
+	console.info( 'isWordPressInstalled', isWordPressInstalled );
```
Comment (ashfame) [inline src/ui/preview/Playground.tsx]: Keeping this here, until we can do `shouldInstallWordPress: 'auto'`

File: src/ui/preview/Playground.tsx [hunk 3]
```diff
@@ -55,9 +56,26 @@ async function initPlayground(
...
+	const mountDescriptor: MountDescriptor = {
+		device: {
+			type: 'opfs',
+			path: '/try-wp-' + slug,
+		},
+		mountpoint: '/wordpress',
+	};
+
+	let isWordPressInstalled = false;
+	if ( localStorage.getItem( 'isWordPressInstalled' ) !== null ) {
```
Comment (psrpinto) [inline src/ui/preview/Playground.tsx]: I think instead of `localStorage` we should use `browser.storage.local`, there's [information about this at MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local):

> Although this API is similar to [Window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), it is recommended that you don't use Window.localStorage in extension code. Firefox clears data stored by extensions using the localStorage API in various scenarios where users clear their browsing history and data for privacy reasons. Data saved using the storage.local API is correctly persisted in these scenarios.

We're using `browser.storage.local` to store other information, take a look at `src/storage`. In the developer tools (Storage tab), you'll see that `isWordPressInstalled` is under "Local Storage", while other extension data is under "Extension Storage".

Note that methods in `browser.storage.local` are async, while in `localStorage` they're synchronous.

File: src/ui/preview/Playground.tsx [hunk 4]
```diff
@@ -68,7 +86,10 @@ async function initPlayground(
 	};
 
 	const client: PlaygroundClient = await startPlaygroundWeb( options );
-	await client.isReady;
+	await client.isReady();
+
+	localStorage.setItem( 'isWordPressInstalled', 'true' );
```
Comment (psrpinto) [inline src/ui/preview/Playground.tsx]: I think we should namespace this with the slug, because otherwise this value will be shared across sessions (aka sites).
```suggestion
	localStorage.setItem( `${slug}-isWordPressInstalled`, 'true' );
```

**Review by psrpinto — COMMENTED** [review]
Persistence now works! It's great to see it finally working, thanks for fixing.

File: src/ui/preview/Playground.tsx (hunk 1 above)
Comment (psrpinto) [reply src/ui/preview/Playground.tsx]: I like that. Hopefully Playground is able to deal with subdirs.

File: src/ui/preview/Playground.tsx (hunk 3 above)
Comment (ashfame) [reply src/ui/preview/Playground.tsx]: TIL! Thank you!

**Review by psrpinto — APPROVED** [review]
